title: Gerard Chicot Navalls
logo: "/images/gerard1.png?raw=true"
description: >
  Máster en Big Data & Data Science por la UCM
  <br><br>
  Graduado en Marketing & Comunicación Digital por EAE Business School
  <br><br>
  Soy una persona a la que le importan las personas y a la que impulsa una voluntad de crecer personal y profesionalmente. Tengo una gran pasión por la analítica de los datos y así poder comprender y transformar la realidad.
  <br><br>
  Kaggler junior! Mejorando día a día gracias a Kaggle.
  <br><br>
  <a href="https://www.linkedin.com/in/gerard-chicot-navalls/">LinkedIn</a>
  <br><br>
  <a href="https://www.kaggle.com/gchicot">Kaggle</a>
  <br><br>
  <a href="https://github.com/GChicot/">GitHub</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 -- Google Analytics tracking ID here
